// Generated by gencpp from file turtlesim_numbers/Numbers.msg
// DO NOT EDIT!


#ifndef TURTLESIM_NUMBERS_MESSAGE_NUMBERS_H
#define TURTLESIM_NUMBERS_MESSAGE_NUMBERS_H

#include <ros/service_traits.h>


#include <turtlesim_numbers/NumbersRequest.h>
#include <turtlesim_numbers/NumbersResponse.h>


namespace turtlesim_numbers
{

struct Numbers
{

typedef NumbersRequest Request;
typedef NumbersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Numbers
} // namespace turtlesim_numbers


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlesim_numbers::Numbers > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::turtlesim_numbers::Numbers&) { return value(); }
};

template<>
struct DataType< ::turtlesim_numbers::Numbers > {
  static const char* value()
  {
    return "turtlesim_numbers/Numbers";
  }

  static const char* value(const ::turtlesim_numbers::Numbers&) { return value(); }
};


// service_traits::MD5Sum< ::turtlesim_numbers::NumbersRequest> should match 
// service_traits::MD5Sum< ::turtlesim_numbers::Numbers > 
template<>
struct MD5Sum< ::turtlesim_numbers::NumbersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim_numbers::Numbers >::value();
  }
  static const char* value(const ::turtlesim_numbers::NumbersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim_numbers::NumbersRequest> should match 
// service_traits::DataType< ::turtlesim_numbers::Numbers > 
template<>
struct DataType< ::turtlesim_numbers::NumbersRequest>
{
  static const char* value()
  {
    return DataType< ::turtlesim_numbers::Numbers >::value();
  }
  static const char* value(const ::turtlesim_numbers::NumbersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlesim_numbers::NumbersResponse> should match 
// service_traits::MD5Sum< ::turtlesim_numbers::Numbers > 
template<>
struct MD5Sum< ::turtlesim_numbers::NumbersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim_numbers::Numbers >::value();
  }
  static const char* value(const ::turtlesim_numbers::NumbersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim_numbers::NumbersResponse> should match 
// service_traits::DataType< ::turtlesim_numbers::Numbers > 
template<>
struct DataType< ::turtlesim_numbers::NumbersResponse>
{
  static const char* value()
  {
    return DataType< ::turtlesim_numbers::Numbers >::value();
  }
  static const char* value(const ::turtlesim_numbers::NumbersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLESIM_NUMBERS_MESSAGE_NUMBERS_H
