// Generated by gencpp from file turtlesim_numbers/NumbersRequest.msg
// DO NOT EDIT!


#ifndef TURTLESIM_NUMBERS_MESSAGE_NUMBERSREQUEST_H
#define TURTLESIM_NUMBERS_MESSAGE_NUMBERSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlesim_numbers
{
template <class ContainerAllocator>
struct NumbersRequest_
{
  typedef NumbersRequest_<ContainerAllocator> Type;

  NumbersRequest_()
    : a(0)
    , b(0)  {
    }
  NumbersRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::turtlesim_numbers::NumbersRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlesim_numbers::NumbersRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NumbersRequest_

typedef ::turtlesim_numbers::NumbersRequest_<std::allocator<void> > NumbersRequest;

typedef boost::shared_ptr< ::turtlesim_numbers::NumbersRequest > NumbersRequestPtr;
typedef boost::shared_ptr< ::turtlesim_numbers::NumbersRequest const> NumbersRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlesim_numbers::NumbersRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlesim_numbers::NumbersRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtlesim_numbers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim_numbers::NumbersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlesim_numbers::NumbersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlesim_numbers::NumbersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlesim_numbers::NumbersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim_numbers::NumbersRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlesim_numbers::NumbersRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlesim_numbers::NumbersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36d09b846be0b371c5f190354dd3153e";
  }

  static const char* value(const ::turtlesim_numbers::NumbersRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36d09b846be0b371ULL;
  static const uint64_t static_value2 = 0xc5f190354dd3153eULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlesim_numbers::NumbersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlesim_numbers/NumbersRequest";
  }

  static const char* value(const ::turtlesim_numbers::NumbersRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlesim_numbers::NumbersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a\n"
"int64 b\n"
;
  }

  static const char* value(const ::turtlesim_numbers::NumbersRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlesim_numbers::NumbersRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NumbersRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlesim_numbers::NumbersRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlesim_numbers::NumbersRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLESIM_NUMBERS_MESSAGE_NUMBERSREQUEST_H
